openshift-assisted/prow-jobs-scraper

- Makefile
- build_deploy.sh
New script to be picked up by the CI and publish the `latest` image and
a version tagged with the commit SHA of the repo.
> Add CI script to publish docker images

- README.md
... and test the integration with app-sre
> NO-ISSUE: Trigger a build of the docker image

- build_deploy.sh
We should tag the image with the first 7 characters of the commit hash.
> NO-ISSUE: Comply with app-sre convention

- Makefile
- openshift/template.yaml
This change adds suspend and schedule parameters because they will be
tuned for integration and stagging.
I also took the oportunity to fix the template and add a target in the
Makefile to lint it.
> NO-ISSUE: Add parameters to the template

- .github/dependabot.yml
Auto-merge dependabot PRs without any manual actions once the tests have
passed.
> NO-ISSUE: Auto approve dependabot PRs

- Makefile
- tests/prowjobsscraper/test_equinix.py
Avoid formatting clashes by using black profile with isort
> NO-ISSUE: use black profile with isort

- .env
- src/prowjobsscraper/prowjob.py
- tests/prowjobsscraper/prowjob_assets/expected_prowjobs.json
- tests/prowjobsscraper/prowjob_assets/valid_prow_response.json
- tests/prowjobsscraper/test_prowjob.py
Compute the job context for rehearse jobs which makes possible to
download equinix metadata for them.
> MGMT-11729: Retrieve equinix metadata from rehearse jobs

- openshift/template.yaml
> test jobs-auto-report

- src/jobsautoreport/main.py
- src/jobsautoreport/models.py
- src/jobsautoreport/query.py
- src/jobsautoreport/report.py
- src/jobsautoreport/slack.py
- tests/jobsautoreport/test_report.py
- tests/jobsautoreport/test_slack.py
This PR is about:
1. Adding the main queries logic.
2. Adjusting the other modules to the new queries.
> MGMT-12708: Implementing the queries (apart from equinix data)

- openshift/template.yaml
Adding elastic search step index environment variable to jobs-auto-report
> MGMT-13001: Adding 'ES_STEP_INDEX' environment variable

- pyproject.toml
- src/jobsautoreport/main.py
- src/jobsautoreport/query.py
- src/jobsautoreport/report.py
- src/jobsautoreport/slack.py
- tests/jobsautoreport/test_report.py
- tests/jobsautoreport/test_slack.py
Currently the report is composed of long lines of data of jobs and steps, which makes it hard to read and extract useful conclusions from it. Therefore I formatted the report to use less words and more visual data. Added figures with `plotly` libray.
> MGMT-13016: Designing the report in a more visual and clear way  

- src/jobsautoreport/report.py
- src/jobsautoreport/slack.py
- tests/jobsautoreport/test_report.py
- tests/jobsautoreport/test_slack.py
Changing the structure of the messages to be one-threaded, adding some debug logs, adding date to the message, adjusting tests
> NO-ISSUE: changing the message format, adding debugging logs

- src/jobsautoreport/main.py
- src/jobsautoreport/slack.py
- tests/jobsautoreport/test_slack.py
1. Changing the report structure to be one-threaded.
2. Changing the start time of the report to be 8AM UTC (10 AM Israel time)
**channel message**
**comments on the message**
> NO-ISSUE: Changing the report structure so it will be one-threaded, changing the report to be 8AM UTC -> 8AM UTC

- src/jobsautoreport/report.py
- src/jobsautoreport/slack.py
- tests/jobsautoreport/test_report.py
- tests/jobsautoreport/test_slack.py
1. Rounding success rates.
2. Setting the sort precedence: First failure rate, then number of failures, and last name.
3. Shortening common jobs names in order to save space.
> NO-ISSUE: Fixes and improvements

- openshift/template.yaml
- pyproject.toml
- src/jobsautoreport/config.py
- src/jobsautoreport/main.py
- src/jobsautoreport/models.py
Env config at: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/56338
> MGMT-13337: Adding monthly report

- .gitignore
> NO-ISSUE: Adding vscode configs to ignored git files

- openshift/template.yaml
Parameterize `equinix` secrets and change their names to fit the convention
> NO-ISSUE: Parameterize equinix secrets and change their names

- openshift/template.yaml
- src/jobsautoreport/config.py
- src/jobsautoreport/main.py
- src/jobsautoreport/query.py
- src/jobsautoreport/report.py
- src/jobsautoreport/slack.py
- tests/jobsautoreport/test_report.py
- tests/jobsautoreport/test_slack.py
Adding `Equinix` total cost metric. It is computed by retrieving the project's usages, and summing all costs of usages from the relevant time interval. 
The new changes in this PR are only the ones in the last commit as it builds on this PR: https://github.com/openshift-assisted/prow-jobs-scraper/pull/140
> MGMT-13001: adding equinix cost metric

- src/jobsautoreport/query.py
- src/prowjobsscraper/equinix_usages.py
- src/prowjobsscraper/main.py
- src/prowjobsscraper/scraper.py
- tests/prowjobsscraper/test_scraper.py
As part of the effort to collect usages correctly, we want to add bandwidth exceed usages to elastic only when their matching regular usage is in the collection interval.
> MGMT-13001: Adjusting collection of bandwidth usages

- src/jobsautoreport/models.py
- src/jobsautoreport/report.py
- src/jobsautoreport/slack.py
- tests/jobsautoreport/test_report.py
- tests/jobsautoreport/test_slack.py
Adding cost by machine type to `equinix` section in the report
> MGMT-13001: Adding cost by machine type metric

- pyproject.toml
- src/jobsautoreport/slack.py
Giving files upload 3 tries to succeed in uploading the files
> NO-ISSUE: Giving files upload have 3 times to success

- src/jobsautoreport/models.py
- src/jobsautoreport/report.py
- src/jobsautoreport/slack.py
- src/prowjobsscraper/scraper.py
- tests/jobsautoreport/test_report.py
- tests/jobsautoreport/test_slack.py
- tests/prowjobsscraper/test_event.py
- tests/prowjobsscraper/test_scraper.py
Adding cost by job type to `equinix` section of the report.
> MGMT-13001: Adding cost by job type

- src/jobsautoreport/plot.py
Changing some of the graphs design as it is not clear enough
new designs:
> MGMT-14591: Changing graphs designs

- src/jobsautoreport/models.py
- src/jobsautoreport/plot.py
- src/jobsautoreport/report.py
- src/jobsautoreport/slack.py
- tests/jobsautoreport/test_report.py
- tests/jobsautoreport/test_slack.py
Converting cost by job type and cost by machine type to a pie chart
> MGMT-14590: Adding pie charts

- src/jobsautoreport/main.py
> NO-ISSUE: Typo fix

- src/jobsautoreport/slack.py
- tests/jobsautoreport/test_slack.py
Removing duplicate minus in trends
> NO-ISSUE: removing redundant minus sign

- pyproject.toml
- src/jobsautoreport/models.py
- src/jobsautoreport/plot.py
- src/jobsautoreport/report.py
- src/jobsautoreport/slack.py
- tests/jobsautoreport/test_report.py
- tests/jobsautoreport/test_slack.py
- tests/jobsautoreport/test_trends.py
In order to get more insights on the reasons of jobs failure, we add a measure of flakiness which is currently the weighted average of absolute difference between adjacent job executions. 
Hence, differences between success and failure in the last execution of job will have more impact on its flakiness score than old jobs
> MGMT-13340: Adding flakiness measure

- src/jobsautoreport/report.py
Reversing flaky jobs so most flaky will be on top
> NO-ISSUE: Reversing flaky jobs

- openshift/template.yaml
Adding another `cronjob` to scrap usages from project `Openshift CI - Bare Metal Single Node` as well
> MGMT-14625: Adding BM SNO costs

- .github/dependabot.yml
> MGMT-15343: dependabot ignore breaking packages

- openshift/template.yaml
Convert boolean openshift parameters to strings
> NO-ISSUE: Fix boolean openshift parameters

- src/jobsautoreport/report.py
Fix Enum value in rehearse jobs
> NO-ISSUE: Fix Enum value in rehearse jobs

- src/jobsautoreport/report.py
NO-ISSUE: Add logs for seeing raw report before sending to slack
> NO-ISSUE: Add logs for seeing raw report before sending to slack

- openshift/template.yaml
Forbid concurrent execution of all cronjobs
> NO-ISSUE: Forbid concurrent execution of all cronjobs

- Dockerfile
- pyproject.toml
> MGMT-15872: Bump python version

- openshift/template.yaml
Parameterize time to live and resources policies
> NO-ISSUE: Parameterize time to live and resources policies

- src/prowjobsscraper/event.py
- tests/prowjobsscraper/test_event.py
Added usage plan for better distinguish between duplicated usages
> NO-ISSUE: Fix usages gather

- openshift/template.yaml
- src/prowjobsscraper/config.py
- src/prowjobsscraper/equinix_metadata.py
- src/prowjobsscraper/main.py
- src/prowjobsscraper/step.py
- src/prowjobsscraper/utils.py
- tests/prowjobsscraper/test_equinix_metadata.py
- tests/prowjobsscraper/test_step.py
Change GCS bucket name in prow jobs scraper
> NO-ISSUE: Change GCS bucket name in prow jobs scraper

- .tekton/prow-jobs-scraper-saas-main-pull-request.yaml
- .tekton/prow-jobs-scraper-saas-main-push.yaml
Task will become mandatory to release, starting November 1st
> MGMT-19174: Add rpms-signature-scan to Konflux pipeline

- .tekton/prow-jobs-scraper-saas-main-pull-request.yaml
- .tekton/prow-jobs-scraper-saas-main-push.yaml
Tasks will become mandatory the 1st of April
> MGMT-20149: Add required sast tasks for Konflux

- src/prowjobsscraper/cir_metadata.py
- tests/prowjobsscraper/cir_metadata_assets/cir_ibm_metadata.json
> NO-ISSUE: Fix IBM provider
