openshift-assisted/prow-jobs-scraper

src/prowjobsscraper/scraper.py, tests/prowjobsscraper/scraper_assets/jobstep.json, tests/prowjobsscraper/test_scraper.py
Adapt the regex on the the job name to catch more assisted jobs (like
subsystem jobs and ai-operator jobs).
=> NO-ISSUE: Adjust filter on job name

src/prowjobsscraper/step.py, tests/prowjobsscraper/step_assets/malformed_time_junit_operator.xml, tests/prowjobsscraper/test_step.py
It looks like the time reported by the junit operator in Prow may be
malformed. As a consequence, prow-job-scraper stops its processing and
nothing is pushed to ES.
This change ignores the error and reports a duration of 0s when the
time is malformed.
=> NO-ISSUE: Handle malformed time in junit

src/prowjobsscraper/equinix.py, tests/prowjobsscraper/test_equinix.py
The name of the step that produces the equinix metadata will change with https://github.com/openshift/release/pull/29138.
=> MGMT-11425: Retrieve equinix metadata from common-gather step

src/prowjobsscraper/equinix.py, tests/prowjobsscraper/test_equinix.py
Handle new step `baremetalds-packet-gather-metadata` to retrieve equinix metadata.
x-ref: https://github.com/openshift/release/pull/32184
=> MGMT-11993: Handle new step to retrieve equinix metadata

Makefile, pyproject.toml
- Bump google-cloud-storage from 2.5.0 to 2.6.0
- Cleanup temporary build directory that prevents the tests to run in Prow
=> NO-ISSUE: upgrade google storage

Dockerfile
The docker image fails to build because the perssions are not set
properly when copying the sources inside the image.
I take also the opportunity of this change to upgrade pip before
installing the application.
=> NO-ISSUE: fix permission issue with docker build

src/jobsautoreport/main.py
Adding a "-*" suffix in order that all jobs indexes will be considered while querying data from elasticsearch
=> MGMT-12553: Adjusting the index_name for queries

src/jobsautoreport/query.py, src/jobsautoreport/utils.py
Searching `jobs` yields only the first 10 results (by default) .
We want to switch from `search` to `scan` which utilizes scrolling, because this way we can:
1. Get all of the documents.
2. Limit the memory usage, because we only generate the next page at each time
=> MGMT-12553: Switching querying method from 'search' to 'scan'

openshift/template.yaml, src/jobsautoreport/main.py, src/jobsautoreport/query.py, src/jobsautoreport/report.py
1. fixing typos.
2. changing the `cronjob` schedule back to `@weekly`
3. formatting job average duration to be composed of minutes and seconds
=> MGMT-12553: fixing some typos, changing the cronjob schedule back to 'weekly', formatting the average job duration to be composed of minutes, seconds

src/jobsautoreport/main.py
At the moment details of the Jobs written to slack is structured as a multi-line string, which forces specific code indentation which does not look good.
Solution: splitting the multi-line string to separated strings.
=> MGMT-12553: Fixing the indentation of lines written to slack

.gitignore, openshift/template.yaml, src/jobsautoreport/config.py, src/jobsautoreport/main.py, src/jobsautoreport/slack.py, tests/jobsautoreport/test_slack.py
Currently the logic for sending messages in `slack`  is based in main module. s part of the app's reconstructing effort, we want to extract the logic to its own class. In addition we switch from `WebhookClient` to `WebClient` a class with capability of commenting on messages in `slack`
=> MGMT-12706: Extracting the slack logic from main

src/jobsautoreport/slack.py, tests/jobsautoreport/test_slack.py
Currently if more than 10 periodic/presubmit jobs are found, we get more than 10 `markdwn` items in the `top_10_failing_e2e_or_subsystem_periodic_jobs` or `top_10_failing_e2e_or_subsystem_presubmit_jobs` (because of the headline), which causes a `SlackApiError`. I changed the message and comment formatting such that each secton will contain maximum of 2 jobs.
=> NO-ISSUE: Change the way the slack message is formatted in order to avoid more than 10 mrkdwn items in a section, which cause a SlackApiError

openshift/template.yaml
Temporarily changing the `backoffLimit` to 4 instead of 3
=> NO-ISSUE: Changing backoffLimit

src/jobsautoreport/report.py, tests/jobsautoreport/test_report.py, tests/jobsautoreport/test_slack.py
`Plotly` presents the records from bottom to top (first element in the list is bottom). In order to present the worse results at the top, I Changed the sorting direction so it will show the worst at the top instead of the bottom, although it is not correct for over than 10 jobs, as it takes the min(10, number_of_jobs) best results, which are not also the 10 worse results in this case. Hence, I changed the sorting to the right direction and just reversed the presentation of them.
=> NO-ISSUE: Fixed sorting wrong way

pyproject.toml, src/prowjobsscraper/event.py, tests/prowjobsscraper/test_event.py
On 01/01/2023, a new index was created because the implementation of
python consisders this day to be the week 0 in year 2023.
We rely on the build_ids inserted in the last 2 indices to make sure we
don't insert the same job twice into ES. Because of this 'ephemeral'
week on day 01/01/2023, we skiped the previous index that was created
(week 52, year 2022) to retrieve the existing build_ids. It led to
insert duplicated jobs.
This change fixes this issue by using the ISO calendar which returns
always the same week consistantly independantly from the current year:
With strftime:
```
>>> date(2023, 1, 1).strftime("%Y.%W")
'2023.00'
>>> date(2022, 12, 30).strftime("%Y.%W")
'2022.52'
```
with isocalendar:
```
>>> date(2023, 1, 1).isocalendar()
datetime.IsoCalendarDate(year=2022, week=52, …
```
=> NO-ISSUE: Use iso calendar to name ES indices

src/jobsautoreport/main.py, src/jobsautoreport/slack.py, tests/jobsautoreport/test_slack.py
1. Changing the report time to - start_time: execution_time - 6 hours - week, end_time: execution_time - 6 hours, this way more jobs are supposed to be finished and indexed in elastic search before execution time.
2. Making the slack message clearer.
=> NO-ISSUE: Changing the report time, making message clearer

src/jobsautoreport/report.py, src/jobsautoreport/slack.py, tests/jobsautoreport/test_report.py, tests/jobsautoreport/test_slack.py
Currently we have some different `postsubmit` jobs that have the same `base_ref`, `repository` and `context`, but different `variant`. slack names are currently composed of `<repository>-<branch>-<context>`, which causes their short slack names to be identical although they are not supposed to be. Hence, we ensure uniqueness of slack names by composing `<repository>-<branch><variant>-<context>` instead, if a group of names variants are not all the same.
=> NO-ISSUE: Add variant to slack name when necessary to avoid name collision

src/prowjobsscraper/equinix_usages.py, src/prowjobsscraper/event.py, src/prowjobsscraper/scraper.py, tests/prowjobsscraper/test_event.py
As a followup to https://github.com/openshift-assisted/prow-jobs-scraper/pull/140, this PR is fixing the way we access retrieved usages. currently when scanning for job build ids for usages in `scan_build_ids_from_index`, we try to access it by `usage` keyword instead of `job`
=> NO-ISSUE: Fix access path to job build_id

src/prowjobsscraper/equinix_usages.py, src/prowjobsscraper/event.py, src/prowjobsscraper/scraper.py, tests/prowjobsscraper/test_event.py, tests/prowjobsscraper/test_scraper.py
Currently `prow-jobs-scraper` scraps usages from `Equinix` metal API in a given interval, and indexes in `elastic` only those whose job's `build_id` is not already indexed. This doesn't work well because jobs can have multiple usages which currently allows only one of them to be indexed. Hence, we change the identifier of a usage to be a tuple of `(name, plan)`, which suppose to be unique.
=> MGMT-13001: Changing the way usage is identified from its corresponding job build's id to a tuple of name and plan

src/prowjobsscraper/equinix_usages.py, src/prowjobsscraper/scraper.py, tests/prowjobsscraper/test_equinix_usages.py, tests/prowjobsscraper/test_scraper.py
Currently, bandwidth usages are obtained from the `Equinix` API using the `start_date` and `end_date` that align with the requested time interval for the API. However, we aim to adjust their time to align with their corresponding non-bandwidth counterpart. This adjustment will allow them to be grouped together in the reports.
=> NO-ISSUE: Changing the bandwidth usages dates to match their non-bandwidth counterpart

src/prowjobsscraper/prowjob.py, src/prowjobsscraper/scraper.py, tests/prowjobsscraper/prowjob_assets/expected_prowjobs.json, tests/prowjobsscraper/test_prowjob.py
Fix scraper to take only public jobs from `Prow`
=> NO-ISSUE: Ignoring private jobs in Prow

src/jobsautoreport/main.py, src/jobsautoreport/slack.py, src/jobsautoreport/trends.py, tests/jobsautoreport/test_slack.py, tests/jobsautoreport/test_trends.py
To track CI trends over time, I included a comparison of each report to its predecessor, focusing on specific attributes of interest.
for example -
=> MGMT-13338: Adding trends over time

src/jobsautoreport/slack.py
We don't want to upload empty graphs when there are no failures
=> NO-ISSUE: Ignoring empty graphs

src/jobsautoreport/slack.py, tests/jobsautoreport/test_slack.py
We remove the arrows as they take too much space
Old:
New:
=> NO-ISSUE: Changing trends design

src/jobsautoreport/report.py, src/jobsautoreport/slack.py, tests/jobsautoreport/test_slack.py
Change flaky jobs in report to include only `periodics`
=> NO-ISSUE: Change flaky jobs in report to include only periodics

openshift/template.yaml, src/prowjobsscraper/config.py, src/prowjobsscraper/equinix_usages.py, src/prowjobsscraper/main.py
Currently, data is collected from `equinix` API at varying intervals but is indexed on a weekly basis. This mismatch leads to some usages being indexed multiple times, damaging the accuracy of the `equinix` cost report. I am setting the usages gather interval to weekly as well.
=> MGMT-15767: Fix scraper's usages gathering

src/jobsautoreport/slack/slack_report.py, tests/jobsautoreport/test_slack_report.py
Disable the `cost by job type` graph until the source of the mismatch between jobs and usages is found, as it causes the graph to be inaccurate.
=> NO-ISSUE: Disable cost by job type

openshift/template.yaml
This will prevent crons execution piling up in case of errors resulting in pending pods i.e.
=> forbid concurrent execution to prevent errors piling up

pyproject.toml, src/prowjobsscraper/event.py, src/prowjobsscraper/utils.py, tests/prowjobsscraper/test_event.py
Currently it is possible for two identical documents to be indexed in the same `elasticsearch` index because in case of parallel execution of `prow-jobs-scraper`, and the fact that we let `elasticsearch` automatically generate `_id` for us. In order to solve this issue I did the following changes:
1.  changed the `_id` to be manually set by us:
- Each jobs index will use job's build id for its id.
- Each steps index will use a hash of `(job_build_id, step.name)` .
- Each usage index will use job's build id.
Each of the above should be unique per index.
2.  changed the bulk actions to "update"
This way, `elasticsearch` will not create duplicated documents in the same index as they have the same `_id`
=> NO-ISSUE: Indexing in elasticsearch with a unique per-index manually set value

.gitignore, pyproject.toml, src/elasticsearch_cleanup/config.py, src/elasticsearch_cleanup/consts.py, src/elasticsearch_cleanup/logger.py, src/elasticsearch_cleanup/main.py, src/elasticsearch_cleanup/models.py, src/elasticsearch_cleanup/utils.py, tests/elasticsearch_cleanup/assets/job_assets.json, tests/elasticsearch_cleanup/assets/step_assets.json, tests/elasticsearch_cleanup/test_main.py, tests/elasticsearch_cleanup/test_utils.py
Currently some `elasticsearch` indices contain duplicated documents. In order to eliminate these duplicates, proposing a utility that knows how to delete duplicates according to a indices-comparison_fields list.
`Cronjob` will be added after setting necessary environment variables in `app-sre`
=> MGMT-15850: Adding a utility to remove Duplicates from elasticsearch indices

openshift/template.yaml, pyproject.toml
Deploy the utility for deleting duplicates from `elasticsearch` indices to `app-sre`
Should follow - https://github.com/openshift-assisted/prow-jobs-scraper/pull/248 and https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/82773
=> MGMT-15851: Deploy the utility for deleting duplicates from elasticsearch indices to app-sre

src/elasticsearch_cleanup/main.py, tests/elasticsearch_cleanup/test_main.py
Currently `elasticsearch-cleanup` uses to much memory for logging the total number of documents and actions. I omitted these logs and used generators instead of lists.
=> NO-ISSUE: Make elasticsearch-cleanup more memory efficient

src/elasticsearch_cleanup/consts.py
The `Scraper` previously relied on Elasticsearch's auto-generated `_id` for document identification. Due to complications arising from parallel scraping, this approach led to the indexing of duplicate documents. To address this, I modified the `_id` assignment for newly scraped documents to use our own identifier, which is based on the `MurmurHash 3`. Furthermore, I adjusted the bulk actions to utilize the `update` method. However, it's important to note that historical documents still retain the Elasticsearch auto-generated `_id`, characterized by strings of letters and dashes. When using the `elasticsearch-cleanup` process to remove duplicates, it can delete the newer documents with the `MurmurHash 3` based `_id`. This happens because the cleanup process simply deletes the second …
=> NO-ISSUE: Sort documents by id in ascending order

.tekton/prow-jobs-scraper-saas-main-pull-request.yaml, .tekton/prow-jobs-scraper-saas-main-push.yaml, Dockerfile
* Add labels
* Add default user
* Add licenses under /licenses/ (dependencies licenses are not taken)
Requirements come from https://docs.redhat.com/en/documentation/red_hat_software_certification/2024/html-single/red_hat_openshift_software_certification_policy_guide/index#additional_resources and would prevent us from releasing an image (we have an exception for "based_on_ubi image")
=> KONFLUX-1611: Add labels, licenses & user to Dockerfile

.tekton/prow-jobs-scraper-saas-main-push.yaml
The tekton pipelines are used by konflux, and the one for push events is broken.
It tries to use a named result that does not exist, the pipeline for pull does not have this problem.
=> MGMT-19125: fix tekton pipeline on push

.tekton/prow-jobs-scraper-saas-main-pull-request.yaml, .tekton/prow-jobs-scraper-saas-main-push.yaml
Remove deprecated task sbom-json-check, because it's causing the release pipeline to fail.
=> NO-ISSUE: remove deprecated task sbom-json-check

src/jobsautoreport/slack/slack_report.py, tests/jobsautoreport/test_slack_report.py
As mentioned in slack API docs:
When a user uploads a file, Slack will scan the file for malware or other suspicious bits before making it available. This means the bigger the file, the longer it might take before your uploaded file is available. As such, we've broken down the uploading process into three steps:
- Call [files.getUploadURLExternal](https://api.slack.com/methods/files.getUploadURLExternal). The response will contain a URL that you can POST the contents of your file to.
POST the contents of your file to the URL returned in step 1. This can be done by sending the raw bytes, or can be a multipart form ended request. If all went well, Slack will respond with an HTTP 200.
- Call [files.completeUploadExternal](https://api.slack.com/methods/files.completeUploadExternal). You can …
=> MGMT-19920: Switch way of uploading files via slack API as the old one is going to be discontinued

src/prowjobsscraper/equinix_metadata.py
This job caused the failure - https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/logs/periodic-ci-openshift-cluster-etcd-operator-release-4.17-periodics-e2e-metal-assisted-four-node-scaling/1908675158332149760/artifacts/e2e-metal-assisted-four-node-scaling/baremetalds-packet-gather-metadata/artifacts/equinix-metadata.json
=> NO-ISSUE: Fix containers failing due to jobs with invalid equinix metadata
